import{a as L,S as w,i as s}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const d of a.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&n(d)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const v="55630805-566a496cfd8411b4d8839b448";async function u(r,t=1){return(await L.get("https://pixabay.com/api/",{params:{key:v,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const p=document.querySelector(".gallery"),f=document.querySelector(".loader"),h=document.querySelector(".button-load"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"simple-lightbox-caption",overlayOpacity:.8});function m(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" width="360" />
      </a>
            <div class="info">
        <p><b>Likes</b> ${o.likes}</p>
        <p><b>Views</b> ${o.views}</p>
        <p><b>Comments</b> ${o.comments}</p>
        <p><b>Downloads</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");p.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){p.innerHTML=""}function y(){f.classList.remove("hidden")}function g(){f.classList.add("hidden")}function b(){h.classList.replace("load-more-hidden","button-load")}function c(){h.classList.replace("button-load","load-more-hidden")}const P=document.querySelector(".form"),R=document.querySelector(".input"),M=document.querySelector(".button-load");M.addEventListener("click",B);let i=1,l="";P.addEventListener("submit",$);async function $(r){if(r.preventDefault(),l=R.value.trim(),i=1,!l){s.warning({message:"Please fill in the search field!",position:"topRight"});return}q(),c(),y();try{const t=await u(l,i);if(t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}m(t.hits);const o=Math.ceil(t.totalHits/15);i>=o?(c(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):b()}catch(t){s.error({message:t.message,position:"topRight"})}finally{g(),r.target.reset()}}async function B(){i++,c(),y();try{const r=await u(l,i);m(r.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"});const n=Math.ceil(r.totalHits/15);i<n?b():(c(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){s.error({message:r.message,position:"topRight"})}finally{g()}}
//# sourceMappingURL=index.js.map
