import{a as L,S as w,i as s}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))n(e);new MutationObserver(e=>{for(const a of e)if(a.type==="childList")for(const c of a.addedNodes)c.tagName==="LINK"&&c.rel==="modulepreload"&&n(c)}).observe(document,{childList:!0,subtree:!0});function o(e){const a={};return e.integrity&&(a.integrity=e.integrity),e.referrerPolicy&&(a.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?a.credentials="include":e.crossOrigin==="anonymous"?a.credentials="omit":a.credentials="same-origin",a}function n(e){if(e.ep)return;e.ep=!0;const a=o(e);fetch(e.href,a)}})();const v="55630805-566a496cfd8411b4d8839b448";async function p(r,t=1){return(await L.get("https://pixabay.com/api/",{params:{key:v,q:r,page:t,per_page:15,image_type:"photo",orientation:"horizontal",safesearch:!0}})).data}const f=document.querySelector(".gallery"),h=document.querySelector(".loader"),m=document.querySelector(".button-load"),S=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"simple-lightbox-caption",overlayOpacity:.8});function y(r){const t=r.map(o=>`
    <li class="gallery-item">
      <a href="${o.largeImageURL}">
        <img src="${o.webformatURL}" alt="${o.tags}" width="360" />
      </a>
            <div class="info">
        <p><b>Likes</b> ${o.likes}</p>
        <p><b>Views</b> ${o.views}</p>
        <p><b>Comments</b> ${o.comments}</p>
        <p><b>Downloads</b> ${o.downloads}</p>
      </div>
    </li>
  `).join("");f.insertAdjacentHTML("beforeend",t),S.refresh()}function q(){f.innerHTML=""}function g(){h.classList.remove("hidden")}function b(){h.classList.add("hidden")}function P(){m.classList.replace("load-more-hidden","button-load")}function d(){m.classList.replace("button-load","load-more-hidden")}const R=document.querySelector(".form"),M=document.querySelector(".input"),u=document.querySelector(".button-load");u.addEventListener("click",B);let i=1,l="";R.addEventListener("submit",$);async function $(r){if(r.preventDefault(),l=M.value.trim(),i=1,!l){s.warning({message:"Please fill in the search field!",position:"topRight"});return}q(),d(),g();try{const t=await p(l,i);if(t.hits.length===0){s.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}y(t.hits);const o=Math.ceil(t.totalHits/15);i>=o?(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"})):P()}catch(t){s.error({message:t.message,position:"topRight"})}finally{b(),r.target.reset()}}async function B(){i++,u.disabled=!0,g();try{const r=await p(l,i);y(r.hits);const o=document.querySelector(".gallery-item").getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"});const n=Math.ceil(r.totalHits/15);i>=n&&(d(),s.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}))}catch(r){s.error({message:r.message,position:"topRight"})}finally{b(),u.disabled=!1}}
//# sourceMappingURL=index.js.map
